In [3]:
import pandas as ninja

data = {
    "calories" : [420,300,350],
    "duration" : [50,40,45]
}
myvari =ninja.DataFrame(data)
print(myvari)

   calories  duration
0       420        50
1       300        40
2       350        45

In [4]:
import pandas as ninja

data = {
    "calories" : [420,300,350],
    "duration" : [50,40,45]
}
myvari =ninja.DataFrame(data)
print(myvari.loc[0])

calories    420
duration     50
Name: 0, dtype: int64

In [5]:
import pandas as ninja

data = {
    "calories" : [420,300,350],
    "duration" : [50,40,45]
}
myvari =ninja.DataFrame(data)
print(myvari.loc[[0,1]])

   calories  duration
0       420        50
1       300        40

In [6]:
import pandas as ninja

data = {
    "calories" : [420,300,350],
    "duration" : [50,40,45]
}
myvari =ninja.DataFrame(data, index = ["day1","day2","day3"])
print(myvari)

      calories  duration
day1       420        50
day2       300        40
day3       350        45

In [13]:
#data cleaning

import pandas as pandu
data = {
    'a' :[420,300,350,None],
    'b': [50,None,40,45],
    'c' : [1,2,None,None]

}

pandi = pandu.DataFrame(data)
print("ori data: \n",pandi)
print()


pandi_cleaner = pandi.dropna()



print("clean data: \n" ,pandi_cleaner)

ori data:
        a     b    c
0  420.0  50.0  1.0
1  300.0   NaN  2.0
2  350.0  40.0  NaN
3    NaN  45.0  NaN

clean data:
        a     b    c
0  420.0  50.0  1.0

In [18]:
import pandas as pandu
data = {
    'a' :[420,300,350,None],
    'b': [50,None,40,45],
    'c' : [1,2,None,None]

}

pandi = pandu.DataFrame(data)
print("ori data: \n",pandi)

pandi.fillna(0,inplace=False)

ori data:
        a     b    c
0  420.0  50.0  1.0
1  300.0   NaN  2.0
2  350.0  40.0  NaN
3    NaN  45.0  NaN

       a     b    c
0  420.0  50.0  1.0
1  300.0   0.0  2.0
2  350.0  40.0  0.0
3    0.0  45.0  0.0

In [19]:
import pandas as pandu
data = {
    'a' :[420,300,350,None],
    'b': [50,None,40,45],
    'c' : [1,2,None,None]

}

pandi = pandu.DataFrame(data)
print("ori data: \n",pandi)

pandi.fillna(pandi.mean(), inplace=False)

ori data:
        a     b    c
0  420.0  50.0  1.0
1  300.0   NaN  2.0
2  350.0  40.0  NaN
3    NaN  45.0  NaN

            a     b    c
0  420.000000  50.0  1.0
1  300.000000  45.0  2.0
2  350.000000  40.0  1.5
3  356.666667  45.0  1.5

In [23]:
import pandas as pandu
data = {
    'a' :[420,350,350,2],
    'b': [50,300,300,45]

}

pandi = pandu.DataFrame(data)
print("ori data: \n",pandi.to_string(index = False))

print("duplicate rows: \n", pandi[pandi.duplicated()].to_string(index=False))


pandi.drop_duplicates(subset = ['a'], keep ='first' , inplace = True)
print("data frame: \n", pandi.to_string(index=False))

ori data:
   a   b
420  50
350 300
350 300
  2  45
duplicate rows:
   a   b
350 300
data frame:
   a   b
420  50
350 300
  2  45

In [25]:
import pandas as pandu
data = {
    'a' :[420,300,350],
    'b': ['papa','papu','pipi'],
    'c' : [50000,5000,500]

}


pani = pandu.DataFrame(data)


pani.rename(columns = {'a' : 'age' ,'b':'name','c': 'salara'},
            inplace = True)
print(pani.to_string(index=False))

 age name  salara
 420 papa   50000
 300 papu    5000
 350 pipi     500